//#include "ui.h"

tMenuItem regionMenuItems[] =
{
    {"Argentina", 	"AR"},
    {"Australia", 	"AU"},
    {"Belgium", 	"BE"},
    {"Brazil", 		"BR"},
    {"Canada", 		"CA"},
    {"Chile", 		"CL"},
    {"Colombia",	"CO"},
    {"Czech Republic", 	"CZ"},
    {"Egypt", 		"EG"},
    {"France", 		"FR"},
    {"Germany", 	"DE"},
    {"Great Britain", 	"GB"},
    {"Hong Kong", 	"HK"},
    {"Hungary", 	"HU"},
    {"India", 		"IN"},
    {"Ireland", 	"IE"},
    {"Israel", 		"IL"},
    {"Italy", 		"IT"},
    {"Japan", 		"JP"},
    {"Jordan", 		"JO"},
    {"Malaysia", 	"MY"},
    {"Mexico", 		"MX"},
    {"Morocco", 	"MA"},
    {"Netherlands", 	"NL"},
    {"New Zealand", 	"NZ"},
    {"Peru", 		"PE"},
    {"Philippines", 	"PH"},
    {"Poland", 		"PL"},
    {"Russia", 		"RU"},
    {"Saudi Arabia", 	"SA"},
    {"Singapore", 	"SG"},
    {"South Africa", 	"ZA"},
    {"South Korea", 	"KR"},
    {"Spain", 		"ES"},
    {"Sweden", 		"SE"},
    {"Taiwan", 		"TW"},
    {"United Arab Emirates","AE"},
    {"United States", 	"US"},
    {NULL, NULL}
};
