//#include "ui.h"

tMenuItem regionMenuItems[] =
{
    {"ALL",  	       "ALL",0},
    {"Argentina", 	"AR",0},
    {"Australia", 	"AU",0},
    {"Belgium", 	"BE",0},
    {"Brazil", 		"BR",0},
    {"Canada", 		"CA",0},
    {"Chile", 		"CL",0},
    {"Colombia",	"CO",0},
    {"Czech Republic", 	"CZ",0},
    {"Egypt", 		"EG",0},
    {"France", 		"FR",0},
    {"Germany", 	"DE",0},
    {"Great Britain", 	"GB",0},
    {"Hong Kong", 	"HK",0},
    {"Hungary", 	"HU",0},
    {"India", 		"IN",0},
    {"Ireland", 	"IE",0},
    {"Israel", 		"IL",0},
    {"Italy", 		"IT",0},
    {"Japan", 		"JP",0},
    {"Jordan", 		"JO",0},
    {"Malaysia", 	"MY",0},
    {"Mexico", 		"MX",0},
    {"Morocco", 	"MA",0},
    {"Netherlands", 	"NL",0},
    {"New Zealand", 	"NZ",0},
    {"Peru", 		"PE",0},
    {"Philippines", 	"PH",0},
    {"Poland", 		"PL",0},
    {"Russia", 		"RU",0},
    {"Saudi Arabia", 	"SA",0},
    {"Singapore", 	"SG",0},
    {"South Africa", 	"ZA",0},
    {"South Korea", 	"KR",0},
    {"Spain", 		"ES",0},
    {"Sweden", 		"SE",0},
    {"Taiwan", 		"TW",0},
    {"United Arab Emirates","AE",0},
    {"United States", 	"US",0},
    {NULL, 		NULL, 0}
};
