#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <time.h>

static void Abort (char *fmt,...)
{
    va_list args;
    va_start (args, fmt);
    vfprintf (stderr, fmt, args);
    va_end (args);
    exit (1);
}

int main (int argc, char **argv)
{
    FILE  *inFile;
    FILE  *outFile = stdout;
    time_t now     = time (NULL);
    int    ch, i;
    char varname[100] = "default.c";

    if (argc != 2 && argc != 3)
        Abort ("Usage: %s bin-file [> result]", argv[0]);

    if ((inFile = fopen(argv[1],"rb")) == NULL)
        Abort ("Cannot open %s\n", argv[1]);

    if (argc == 3)
        strcpy((char*) varname, argv[2]);

    fprintf (outFile,
             "/* data statements for file %s at %.24s */\n"
             "/* Generated by BIN2C, G.Vanem 1995 */\n",
             argv[1], ctime(&now));

    fprintf(outFile, "const char  %s_data[] = {\n", varname);

    i = 0;
    while ((ch = fgetc(inFile)) != EOF)
    {
        if (i++ % 12 == 0)
            fputs ("\n  ", outFile);
        fprintf (outFile, "0x%02X,", ch);
    }
    fputc ('\n', outFile);

    fprintf (outFile, "};\nconst unsigned int %s_size = sizeof(%s_data);\n\n", varname, varname);

    fclose (inFile);
    return (0);
}
